package com.example.financialhealth.model;

import jakarta.persistence.*;
import lombok.*; // Added
import lombok.EqualsAndHashCode.Include; // Added
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.sql.Timestamp;
// Removed java.util.Objects

@Getter // Lombok
@Setter // Lombok
@NoArgsConstructor // Lombok
@AllArgsConstructor // Lombok
@EqualsAndHashCode(onlyExplicitlyIncluded = true) // Lombok
@ToString(exclude = {"user", "category"}) // Lombok
@Entity
@Table(name = "budgets", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"user_id", "category_id", "month"})
})
public class Budget {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Include // For Lombok @EqualsAndHashCode
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "category_id", nullable = false)
    private Category category;

    @Column(name = "allocated_amount", nullable = false, precision = 19, scale = 4)
    private BigDecimal allocatedAmount;

    @Column(nullable = false, length = 7) // YYYY-MM format
    private String month;

    @Column(name = "total_monthly_budget_goal", precision = 19, scale = 4) // Nullable
    private BigDecimal totalMonthlyBudgetGoal;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Timestamp createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Timestamp updatedAt;

    // Manual constructors, getters, setters, equals, hashCode are removed.
    // The previous constructor:
    // public Budget(User user, Category category, BigDecimal allocatedAmount, String month, BigDecimal totalMonthlyBudgetGoal)
    // will be generated by @AllArgsConstructor.
}
